import type { Metadata } from 'next';
import './globals.css';
import { dmSans, geistMono, geistSans, poppins, productSans } from './fonts';
import { Toaster } from '@/components/ui/sonner';
import HOC from '@/components/shared/hoc/HOC';
import Footer from '@/config/marginals/Footer';

export const metadata: Metadata = {
  title: 'DSC NIT Rourkela',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${dmSans.variable} ${productSans.variable}  antialiased`}
      >
        <Toaster position="top-right" />
        <HOC>{children}</HOC>
        <Footer />
      </body>
    </html>
  );
}
